MODULE CONSTANTES
    USE, INTRINSIC :: ISO_FORTRAN_ENV
    IMPLICIT NONE

    ! constantes
    INTEGER, PARAMETER :: sp = REAL32
    INTEGER, PARAMETER :: dp = REAL64
    INTEGER, PARAMETER :: qp = REAL128

    INTEGER, PARAMETER :: rp = dp

    REAL(rp), PARAMETER :: pi = 2._rp * ACOS(0._rp)
END MODULE CONSTANTES